filetype off
call pathogen#infect()
call pathogen#helptags()

filetype on

set number
set hlsearch

set foldmethod=indent
set foldlevel=99

map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

map <F4> :NERDTreeToggle<CR>
